import "dotenv/config";

const { env } = process;
const {
  DATABASE_NAME,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_PASS,
  PORT,
  JWT_SECRET,
  JWT_SECRET_EXPIRATION_TIME,
  JWT_REFRESH_SECRET_EXPIRATION_TIME,
  NODE_ENV,
  JWT_REFRESH_SECRET
} = env;

const DATABASE: any = {
  DATABASE_NAME,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_PASS,
};

const GLOBAL_CONFIGS = { DATABASE, PORT, JWT_SECRET, JWT_SECRET_EXPIRATION_TIME, NODE_ENV, JWT_REFRESH_SECRET, JWT_REFRESH_SECRET_EXPIRATION_TIME };
export default GLOBAL_CONFIGS;
